#!/usr/bin/env python3
import argparse
import datetime
import time
import urllib.parse

import requests


DEFAULT_BASE = 'http://localhost:8090/'
PATHS = {
    'config': "/burp/configuration",
    'history': "/burp/proxy/history",
    'issues': "/burp/scanner/issues",
    'report': "/burp/report",
    'scan-active': "/burp/scanner/scans/active",
    'scan-passive': "/burp/scanner/scans/passive",
    'scan-status': "/burp/scanner/status",
    'sitemap': "/burp/target/sitemap",
    'spider': "/burp/spider",
    'spider-status': "/burp/spider/status",
    'stop': "/burp/stop",
    'target': "/burp/target/scope",
    # '': "/burp/versions" ,
}


class BurpClient:
    def __init__(self, base_url=''):
        '''paths should be a dictionary of action:path'''
        if not base_url:
            raise Exception('Missing base url')
        self.base_url = base_url

    def _resource_url(self, action):
        return urllib.parse.urljoin(self.base_url, PATHS[action])

    def target_in_scope(self, target):
        url = self._resource_url('target')
        params = {'url': target}
        resp = requests.get(url, params=params)
        if not resp.ok:
            print('i clearly don\'t know how to handle errors. target-in-scope failed')
            return False
        try:
            data = resp.json()
            return data['inScope']
        except Exception:
            return 'Failed to parse response data: {}'.format(resp.text)

    def target_add(self, target):
        url = self._resource_url('target')
        data = {'url': target}
        resp = requests.put(url, data=data)
        if resp.ok:
            return 'Added {} to scope'.format(target)
        else:
            return 'Failed to add {} to scope'.format(target)

    # TODO add like, filtering or something (either here or in cli/app code) so you
    # can do things like... emit errors or whatever when you find an issue
    def issues(self, target):
        '''Get the issues found for a target'''
        url = self._resource_url('issues')
        data = {'url': target}
        return url, data

    def spider(self, target):
        '''Send a seed URL to the Burp spider (which queues it for spidering)'''
        url = self._resource_url('spider')
        data = {
            'baseUrl': target
        }
        resp = requests.post(url, data=data)
        if resp.ok:
            return 'Sent {} to be spidered.'.format(target)
        else:
            return 'Failed to send URL! Status {}, {}'.format(resp.status_code, resp.text)

    def spider_status(self):
        '''Returns msg and True/False for done/not done'''
        url = self._resource_url('spider-status')
        resp = requests.get(url)
        if not resp.ok:
            return (
                'Failed to get status! Status {}, {}'.format(resp.status_code, resp.text),
                False
            )
        try:
            data = resp.json()
            perc = data['spiderPercentage']
            return 'Spider percentage: {}'.format(perc), perc == 100
        except Exception:
            return 'Failed to parse response data: {}'.format(resp.text), False

    def sitemap(self, base='', json=False):
        '''Return the sitemap as a dict or json string. Provide base if you want the map
        for only a specific prefix.'''
        url = self._resource_url('sitemap')
        resp = requests.get(url, params={'urlPrefix': base})
        if not resp.ok:
            return 'Failed to get sitemap! Status {}, {}'.format(resp.status_code, resp.text),
        try:
            d = resp.json()  # ensure that it's actually JSON
            if json:
                return resp.text
            return d
        except Exception:
            return 'Failed to parse response data: {}'.format(resp.text)

    def scan_active(self, target):
        url = self._resource_url('scan-active')
        resp = requests.post(url, data={'baseUrl': target})
        if not resp.ok:
            return 'Failed start scan! Status {}, {}'.format(resp.status_code, resp.text)
        return 'Started active scan on {}'.format(target)

    def scan_passive(self, target):
        url = self._resource_url('scan-passive')
        resp = requests.post(url, data={'baseUrl': target})
        if not resp.ok:
            return 'Failed start scan! Status {}, {}'.format(resp.status_code, resp.text)
        return 'Started passive scan on {}'.format(target)

    def scan_status(self):
        '''Returns text and True/False for done/not done'''
        url = self._resource_url('scan-status')
        resp = requests.get(url)
        if not resp.ok:
            return (
                'Failed to get status! Status {}, {}'.format(resp.status_code, resp.text),
                False
            )
        try:
            data = resp.json()
            perc = data['scanPercentage']
            return 'Scan percentage: {}'.format(perc), perc == 100
        except Exception:
            return 'Failed to parse response data: {}'.format(resp.text), False

    def report(self):
        url = self._resource_url('report')
        resp = requests.get(url)
        if not resp.ok:
            print('Failed to get status! Status {}, {}'.format(resp.status_code, resp.text))
            return
        return resp.text

    def stop(self):
        '''Stop Burp. Per the docs, this *fully stops* the burp process.'''
        url = self._resource_url('stop')
        resp = requests.get(url)
        if not resp.ok:
            return 'Failed to stop Burp! {}'.format(resp.text)
        else:
            return 'Successfully stopped Burp.'


def _wait_print_status(f):
    '''call the fn wait til it returns true... but it's obviously intended for the
    client lel idc

    f should return a msg and a bool status, True for done, False for not'''
    completed = False
    try:
        start = datetime.datetime.now()
        while not completed:
            msg, completed = f()
            print('{}'.format(msg), end='\r')
            time.sleep(1)
        print()
        print('Done in {}'.format(datetime.datetime.now() - start))
    except KeyboardInterrupt:
        print()
        print('Caught keyboard interrupt. Note that the job may still be running!')


def report_cmd(client, args):
    with open(args.output, 'x') as f:
        report = client.report()
        if report:
            f.write(report)
            print('Wrote out report to {}'.format(args.output))


def spider_cmd(client, args):
    url = args.url
    if url:
        if args.add_to_scope:
            client.target_add(url)
        print(client.spider(url))
    if args.status:
        _wait_print_status(client.spider_status)


def scan_cmd(client, args):
    # wait is this how programming works lol
    url = args.url
    if url:
        if args.add_to_scope:
            print(client.target_add(url))
            spider_cmd(client, args)  # lol
        if args.passive:
            print(client.scan_passive(url))
        else:
            print(client.scan_active(url))
    if args.status:
        _wait_print_status(client.scan_status)


def sitemap_cmd(client, args):
    print(client.sitemap(json=True, base=args.url))


def stop_cmd(client, _):
    print(client.stop())


if __name__ == '__main__':
    root = argparse.ArgumentParser(description='CLI for Burp Rest API')
    root.set_defaults(cmd='')  # stupid hack to keep a record of the subcommand used
    root.add_argument('-b', '--base', help='Base Burp daemon URL',
                      metavar='base', type=str, default='')
    root.add_argument('-f', '--file', help='YAML file of urls to scan',
                      metavar='base', type=str, default='')
    subparsers = root.add_subparsers()

    spider = subparsers.add_parser('spider', help='Subcommands for the Burp spider')
    spider.set_defaults(cmd='spider')  # stupid hack to keep a record of the subcommand used

    # all subcommands can be changed to use choices and positional args instead of flags (for some options)
    spider.add_argument('-u', '--url', help='Send a URL to the spider queue',
                        metavar='url', type=str, default='')
    spider.add_argument('-s', '--status', help='Get the current spider status',
                        action='store_true')
    spider.add_argument('-a', '--add-to-scope', help='Add the URL to the scope if it isn\'t in scope already',
                        action='store_true', default=False)

    scan = subparsers.add_parser('scan', help='Subcommands for the Burp active scanner')
    scan.set_defaults(cmd='scan')  # stupid hack to keep a record of the subcommand used
    scan.add_argument('-u', '--url', help='Target URL',
                      metavar='url', type=str, nargs='?')
    scan.add_argument('-a', '--add-to-scope', help='Add the URL to the scope if it isn\'t in scope already',
                      action='store_true', default=True)
    scan.add_argument('-p', '--passive', help='Do a passive scan',
                      action='store_true')
    scan.add_argument('-s', '--status', help='Get the current scanner status',
                      action='store_true')

    report = subparsers.add_parser('report', help='Get the scan report')
    report.set_defaults(cmd='report')  # stupid hack to keep a record of the subcommand used
    report.add_argument('-o', '--output', help='Output file for report',
                        required=True, type=str)

    sitemap = subparsers.add_parser('sitemap', help='Get the current sitemap')
    sitemap.set_defaults(cmd='sitemap')  # stupid hack to keep a record of the subcommand used
    sitemap.add_argument('-u', '--url', help='Target URL',
                         metavar='url', type=str, default='')

    stop = subparsers.add_parser('stop', help='Stop the Burp daemon')
    stop.set_defaults(cmd='stop')  # stupid hack to keep a record of the subcommand used

    args = root.parse_args()

    # time to actually do stuff
    base_url = args.base or DEFAULT_BASE
    client = BurpClient(base_url)
    # TODO technically can go as a constant but i'd like to clean up other things first
    COMMANDS = {
        'spider': spider_cmd,
        'scan': scan_cmd,
        'stop': stop_cmd,
        # 'target': target_cmd,
        'sitemap': sitemap_cmd,
        'report': report_cmd
    }

    try:
        cmd = COMMANDS[args.cmd]
        cmd(client, args)
    except KeyError:
        root.print_help()
    except requests.exceptions.ConnectionError as e:
        print('Couldn\'t connect to the Burp daemon at {}.\n'
              'Is it running?'.format(base_url))
